### ISSUE TITLE
tagging数据集的部分错误

### ISSUE THREAD

**Issue by Linzijiandevx24** [open-event-hub/title2event_baselines#1]
title_id为36700 25830 32017 19950 26843 24843 
tagging训练集中trg-tags没有标注好的

**Comment by HarlynDN** [comment]
您好，
所有的tagging都是根据ground truth label自动标注的（论文5.2节），因此在一些样本上会出现无法标注的情况，我们认为这是tagging based methods在我们任务上的局限性（论文6.3节），所有方法的实验结果都是直接使用ground truth label进行评估的。

**Comment by Linzijiandevx24** [comment]
了解，感谢回复
