### ISSUE TITLE
AttributeError: 'QuestionAnsweringSeq2SeqTrainer' object has no attribute '_gen_kwargs'

### ISSUE THREAD

**Issue by up-up-liang** [open-event-hub/title2event_baselines#2]
你好，我在运行run_seq2seq_qa.py在golden triggers上训练的时候，出现下图错误，
![image](https://user-images.githubusercontent.com/59355616/228432500-431b4188-3a43-4c70-aca9-5f90333d1071.png)
请问，我修改过transformers（4.19.0或4.27.0、4.27.1）的版本，不起作用。
如果你遇到过这个问题，能够告知如何解决的，感谢

**Comment by HarlynDN** [comment]
您好，
该问题应该是由于transformers从v4.21.0开始修改了Seq2SeqTrainer.evaluate方法的入口参数。

[v4.20.1版本](https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/trainer#transformers.Seq2SeqTrainer.evaluate)
![image](https://user-images.githubusercontent.com/45941630/229348094-47619366-3dd2-49c5-812c-e64e1f9940d7.png)

[v4.21.0版本](https://huggingface.co/docs/transformers/v4.21.3/en/main_classes/trainer#transformers.Seq2SeqTrainer.evaluate)
![image](https://user-images.githubusercontent.com/45941630/229348164-c4110060-71f5-4c2b-89ac-361f0819107a.png)

因此请确保您使用的版本<=v4.20.1，可以查看transformers源代码确认Seq2SeqTrainer.evaluate的实现符合哪一个版本，如有问题欢迎继续沟通。

**Comment by up-up-liang** [comment]
> 您好， 该问题应该是由于transformers从v4.21.0开始修改了Seq2SeqTrainer.evaluate方法的入口参数。
> 
> [v4.20.1版本](https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/trainer#transformers.Seq2SeqTrainer.evaluate) ![image](https://user-images.githubusercontent.com/45941630/229348094-47619366-3dd2-49c5-812c-e64e1f9940d7.png)
> 
> [v4.21.0版本](https://huggingface.co/docs/transformers/v4.21.3/en/main_classes/trainer#transformers.Seq2SeqTrainer.evaluate) ![image](https://user-images.githubusercontent.com/45941630/229348164-c4110060-71f5-4c2b-89ac-361f0819107a.png)
> 
> 因此请确保您使用的版本<=v4.20.1，可以查看transformers源代码确认Seq2SeqTrainer.evaluate的实现符合哪一个版本，如有问题欢迎继续沟通。

感谢您的解答，按照您的方法，我把transformers版本更新为v4.20.1，问题解决了，谢谢！
