### ISSUE TITLE
environment setting

### ISSUE THREAD

**Issue by xiehou-design** [open-event-hub/title2event_baselines#3]
Can you provide a detail environment setting? I met many environment setting problem when I reprodected it.
`  File "run_ner.py", line 500, in main
    metric = evaluate.load('seqeval')
  File "/media/ubuntu/projects/xiehou/anaconda3/envs/titleEE/lib/python3.8/site-packages/evaluate/loading.py", line 735, in load
    evaluation_instance = evaluation_cls(
TypeError: 'NoneType' object is not callable`

**Comment by HarlynDN** [comment]
Hi,
I just tried `evaluate.load('seqeval')` using the latest version of `evaluate` and `seqeval`, and everything worked fine.
Did you manually download the metric file and put it in your local directory? Maybe you can check this: https://github.com/huggingface/evaluate/issues/257

**Comment by xiehou-design** [comment]
> Hi, I just tried `evaluate.load('seqeval')` using the latest version of `evaluate` and `seqeval`, and everything worked fine. Did you manually download the metric file and put it in your local directory? Maybe you can check this: [huggingface/evaluate#257](https://github.com/huggingface/evaluate/issues/257)

thannk you, I try the latest version of transformer, evaluate and seqeval, the code is work. Only replace `metric = evaluate.load('seqeval')` to `metric = evaluate.load('./seqeval/')`, and follow this issue [https://github.com/huggingface/evaluate/issues/257](https://github.com/huggingface/evaluate/issues/257)  to download `seqeval.py`.
