### ISSUE TITLE
perfomance gap

### ISSUE THREAD

**Issue by FredlinT** [open-event-hub/title2event_baselines#4]
我试了trigger的模型训练，是用代码里面的默认参数在数据集上的效果表现和论文差距有点大， 验证集上p/r/f1为：0.6177/0.6298/0.6237，测试集合上p/r/f1为：0.6155/0.6336/0.6244，请问是什么情况呢

**Comment by HarlynDN** [comment]
抱歉未能及时回复。Trigger Extraction训练代码里面的evaluator是评估序列标注任务的指标seqeval，而论文中汇报的分数是事件三元组抽取的评估结果，基于exact match。想要复现论文结果的分数请使用提供的评估代码evaluation.py

**Comment by FredlinT** [comment]
好的，我尝试下， 感谢回复，

**Comment by HarlynDN** [comment]
如还有问题欢迎重开这个 issue
